import { NgModule } from '@angular/core';

import {
  MdToolbarModule,
  MdButtonModule,
  MdIconModule,
  MdCardModule,
  MdInputModule,
  MdGridListModule,
  MdMenuModule,
  MdTabsModule,
  MdListModule,
  MdLineModule,
  MdChipsModule,
  MdSelectModule,
  MdRippleModule,
  MdSliderModule,
  MdSidenavModule,
  MdSnackBarModule,
  MdDatepickerModule,
  MdNativeDateModule,
  MdCoreModule,
  MdRadioModule,
  MdDialogModule,
  MdCommonModule,
  MdSlideToggleModule,
  MdButtonToggleModule,
  
 } from '@angular/material';

@NgModule({
  imports: [
    MdToolbarModule,
    MdButtonModule,
    MdIconModule,
    MdCardModule,
    MdInputModule,
    MdGridListModule,
    MdMenuModule,
    MdTabsModule,
    MdListModule,
    MdLineModule,
    MdChipsModule,
    MdSelectModule,
    MdRippleModule,
    MdSliderModule,
    MdSidenavModule,
    MdSnackBarModule,
    MdDatepickerModule,
    MdNativeDateModule,
    MdCoreModule,
    MdRadioModule,
    MdDialogModule,
    MdCommonModule,
    MdSlideToggleModule,
    MdButtonToggleModule,
  ],
  exports: [
    MdToolbarModule,
    MdButtonModule,
    MdIconModule,
    MdCardModule,
    MdInputModule,
    MdGridListModule,
    MdMenuModule,
    MdTabsModule,
    MdListModule,
    MdLineModule,
    MdChipsModule,
    MdSelectModule,
    MdRippleModule,
    MdSliderModule,
    MdSidenavModule,
    MdSnackBarModule,
    MdDatepickerModule,
    MdNativeDateModule,
    MdCoreModule,
    MdRadioModule,
    MdDialogModule,
    MdCommonModule,
    MdSlideToggleModule,
    MdButtonToggleModule,
  ],
  declarations: []
})
export class ImportMaterialComponentsModule { }
